---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap
    - role: raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - role: k3s_agent

- name: Istio, Knative
  hosts: server
  become: true
  roles:
    - role: istio_knative

- name: Kserve
  hosts: server
  become: true
  roles:
    - kserve  

- name: Prepare Cluster for GitOps
  hosts: server
  become: true
  roles:
    - role: argo_cd

- name: Installing Prometheus and Grafana for monitoring
  hosts: server
  become: true
  roles:
    - role: prometheus_grafana